figure;
% xlable('gary scale range');
% ylable('intensity');
img =cast(img,'uint8');
subplot(1,5,1);
hist_img=histeq(img);
title('hist quantization image');
subplot(1,5,2);
imhist(img);
title('original');
subplot(1,5,3);
powerlaw_img=cast(powerlaw_img,'uint8');
imhist(powerlaw_img);
title('powerlaw');
subplot(1,5,4);
neg=cast(neg,'uint8');
imhist(neg);
title('negative');
subplot(1,5,5);
log_img=cast(log_img,'uint8');
imhist(log_img);
title('logarithmic');